export const accounts = [
    {
      NomorAkun: "1-0000",
      NamaAkun: "Aktiva",
      PosSaldo: "-",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "1-1100",
      NamaAkun: "Kas",
      PosSaldo: "Db",
      NeracaDebit: 24800000,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 24800000,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "1-1200",
      NamaAkun: "Piutang",
      PosSaldo: "Db",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "1-1300",
      NamaAkun: "Perlengkapan",
      PosSaldo: "Db",
      NeracaDebit: 150000,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 150000,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "1-1400",
      NamaAkun: "Persediaan Aset Biologis",
      PosSaldo: "Db",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "1-2100",
      NamaAkun: "Lahan Pertanian",
      PosSaldo: "Db",
      NeracaDebit: 50000000,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 50000000,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "1-2200",
      NamaAkun: "Peralatan",
      PosSaldo: "Db",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "1-2210",
      NamaAkun: "Akumulasi Penyusutan Peralatan",
      PosSaldo: "Cr",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "2-0000",
      NamaAkun: "Kewajiban",
      PosSaldo: "-",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "2-1100",
      NamaAkun: "Utang Usaha",
      PosSaldo: "Cr",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "2-2100",
      NamaAkun: "Utang Jangka Panjang",
      PosSaldo: "Cr",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "3-0000",
      NamaAkun: "Ekuitas",
      PosSaldo: "-",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "3-1100",
      NamaAkun: "Modal",
      PosSaldo: "Cr",
      NeracaDebit: 0,
      NeracaKredit: 69000000,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 69000000
    },
    {
      NomorAkun: "3-1200",
      NamaAkun: "Laba",
      PosSaldo: "Db",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "NRC",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "4-0000",
      NamaAkun: "Pendapatan",
      PosSaldo: "-",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "LR",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "4-1100",
      NamaAkun: "Penjualan Biji Kopi",
      PosSaldo: "Cr",
      NeracaDebit: 0,
      NeracaKredit: 11500000,
      PosLaporan: "LR",
      LabaRugiDebit: 0,
      LabaRugiKredit: 11500000,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "4-1200",
      NamaAkun: "Retur Penjualan",
      PosSaldo: "Db",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "LR",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "6-0000",
      NamaAkun: "Beban-Beban Usaha",
      PosSaldo: "-",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "LR",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "6-1100",
      NamaAkun: "Beban Pupuk",
      PosSaldo: "Db",
      NeracaDebit: 200000,
      NeracaKredit: 0,
      PosLaporan: "LR",
      LabaRugiDebit: 200000,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    },
    {
      NomorAkun: "6-1200",
      NamaAkun: "Beban Penyusutan",
      PosSaldo: "Db",
      NeracaDebit: 0,
      NeracaKredit: 0,
      PosLaporan: "LR",
      LabaRugiDebit: 0,
      LabaRugiKredit: 0,
      NeracaSaldoDebit: 0,
      NeracaSaldoKredit: 0
    }
  ];
